// This file was auto-generated by Fern from our API Definition.

export interface Error_ {
    error: Error_.Error_;
}

export namespace Error_ {
    export interface Error_ {
        /**
         * Branch on this, not on the message.
         *
         * `UNAVAILABLE` (503, with `Retry-After`) means authorization could not be
         * decided right now. Retry; it says nothing about whether the resource exists.
         *
         * There is deliberately no "forbidden" or "permission denied" member.
         * A resource you may not reach is reported as `NOT_FOUND`, identically
         * to one that does not exist.
         */
        code: Error_.Code;
        /** Human-readable. Not stable; do not parse it. */
        message: string;
        /** Also returned as `X-Request-Id`. Quote it in support requests. */
        request_id: string;
    }

    export namespace Error_ {
        /**
         * Branch on this, not on the message.
         *
         * `UNAVAILABLE` (503, with `Retry-After`) means authorization could not be
         * decided right now. Retry; it says nothing about whether the resource exists.
         *
         * There is deliberately no "forbidden" or "permission denied" member.
         * A resource you may not reach is reported as `NOT_FOUND`, identically
         * to one that does not exist.
         */
        export const Code = {
            NotFound: "NOT_FOUND",
            InvalidRequest: "INVALID_REQUEST",
            Conflict: "CONFLICT",
            RateLimited: "RATE_LIMITED",
            Internal: "INTERNAL",
            Unavailable: "UNAVAILABLE",
            Unauthenticated: "UNAUTHENTICATED",
        } as const;
        export type Code = (typeof Code)[keyof typeof Code];
    }
}
