// This file was auto-generated by Fern from our API Definition.

export interface Grant {
    subject_type?: Grant.SubjectType | undefined;
    subject_id?: string | undefined;
    role?: Grant.Role | undefined;
    scope_type?: Grant.ScopeType | undefined;
    scope_id?: string | undefined;
    created_at?: string | undefined;
    /** Present and true when this was an idempotent replay. */
    replayed?: boolean | undefined;
}

export namespace Grant {
    export const SubjectType = {
        User: "user",
        Group: "group",
    } as const;
    export type SubjectType = (typeof SubjectType)[keyof typeof SubjectType];
    export const Role = {
        Viewer: "viewer",
        Editor: "editor",
        Manager: "manager",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
    export const ScopeType = {
        Document: "document",
        Folder: "folder",
        Tenant: "tenant",
    } as const;
    export type ScopeType = (typeof ScopeType)[keyof typeof ScopeType];
}
