// This file was auto-generated by Fern from our API Definition.

export interface HealthStatus {
    status: HealthStatus.Status;
    /**
     * The build this process is serving — the deploying platform's commit sha, or an
     * explicit release name where one is set. `unknown` when nothing stamped the build,
     * which is every local run; the field is always present, so an unstamped build can
     * be told apart from a deployment that predates the field (#786).
     */
    build: string;
}

export namespace HealthStatus {
    export const Status = {
        Ok: "ok",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
