// This file was auto-generated by Fern from our API Definition.

export const RevokeGrantRequestRole = {
    Viewer: "viewer",
    Editor: "editor",
    Manager: "manager",
    Reader: "reader",
    Writer: "writer",
    Approver: "approver",
} as const;
export type RevokeGrantRequestRole = (typeof RevokeGrantRequestRole)[keyof typeof RevokeGrantRequestRole];
