// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         subject_type: "user",
 *         subject_id: "subject_id",
 *         role: "viewer",
 *         scope_type: "document",
 *         scope_id: "scope_id"
 *     }
 */
export interface CreateGrantRequest {
    /**
     * A unique string per logical operation, at most 255 printable ASCII
     * characters. Retrying with the same key and body returns the first outcome
     * instead of acting twice. Idempotency keys are scoped to your key's principal
     * and expire after 24 hours; that expiry is on the replay key, not on your API
     * key.
     */
    "Idempotency-Key": string;
    subject_type: CreateGrantRequest.SubjectType;
    subject_id: string;
    /** viewer, editor or manager. reader, writer and approver are deprecated aliases. */
    role: CreateGrantRequest.Role;
    scope_type: CreateGrantRequest.ScopeType;
    /**
     * `handbook` for a folder, `handbook/policies` for a nested one,
     * `handbook/policies/leave.md` for a document.
     */
    scope_id: string;
}

export namespace CreateGrantRequest {
    export const SubjectType = {
        User: "user",
        Group: "group",
    } as const;
    export type SubjectType = (typeof SubjectType)[keyof typeof SubjectType];
    /** viewer, editor or manager. reader, writer and approver are deprecated aliases. */
    export const Role = {
        Viewer: "viewer",
        Editor: "editor",
        Manager: "manager",
        Reader: "reader",
        Writer: "writer",
        Approver: "approver",
    } as const;
    export type Role = (typeof Role)[keyof typeof Role];
    export const ScopeType = {
        Document: "document",
        Folder: "folder",
        Tenant: "tenant",
    } as const;
    export type ScopeType = (typeof ScopeType)[keyof typeof ScopeType];
}
