// This file was auto-generated by Fern from our API Definition.

import type * as AgentlefsApi from "../../../../index.js";

/**
 * @example
 *     {
 *         scope_type: "document",
 *         scope_id: "scope_id"
 *     }
 */
export interface ListGrantsRequest {
    /**
     * Which kind of thing `scope_id` names. Required and never inferred: a document
     * and a directory can share a path and are different scopes with different
     * grants.
     */
    scope_type: AgentlefsApi.ListGrantsRequestScopeType;
    /** The scope, slash-joined. `handbook`, `handbook/policies`, `handbook/leave.md`. */
    scope_id: string;
}
