// This file was auto-generated by Fern from our API Definition.

import type * as AgentlefsApi from "../../../../index.js";

/**
 * @example
 *     {
 *         subject_type: "user",
 *         subject_id: "subject_id",
 *         role: "viewer",
 *         scope_type: "document",
 *         scope_id: "scope_id"
 *     }
 */
export interface RevokeGrantRequest {
    subject_type: AgentlefsApi.RevokeGrantRequestSubjectType;
    subject_id: string;
    /** viewer, editor or manager. reader, writer and approver are deprecated aliases. */
    role: AgentlefsApi.RevokeGrantRequestRole;
    /**
     * Which kind of thing `scope_id` names. Required and never inferred: a document
     * and a directory can share a path and are different scopes with different
     * grants.
     */
    scope_type: AgentlefsApi.RevokeGrantRequestScopeType;
    /** The scope, slash-joined. `handbook`, `handbook/policies`, `handbook/leave.md`. */
    scope_id: string;
}
