// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "If-Match": "If-Match",
 *         location: "handbook/onboarding/day-one.md"
 *     }
 */
export interface DeleteDocumentRequest {
    /**
     * The document's whole path from the workspace root, filename included,
     * URL-encoded once.
     *
     * The path separators may be sent either way. `handbook/onboarding/day-one.md`
     * and `handbook%2Fonboarding%2Fday-one.md` address the same document, because
     * the value is decoded exactly once before it is used. Write whichever is more
     * natural: a handwritten request usually uses literal separators, while a
     * generated SDK client will percent-encode them, since OpenAPI requires a path
     * parameter's reserved characters to be escaped.
     *
     * What is rejected, in either spelling, is a path that does not mean one
     * definite location: an empty segment (`//`) or a relative segment (`.`, `..`)
     * is a `400`, whether written literally or percent-encoded.
     *
     * This was the document's path WITHIN a folder, alongside a required `folder`
     * query parameter. One location replaces both.
     */
    location: string;
    /**
     * The `ETag` from a whole-document read or from a write to it, or `*` to act
     * unconditionally. A ranged read (`offset`) tags the excerpt it returned, not the
     * document, so its tag is not a version to send back here.
     */
    "If-Match": string;
}
