// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         from: "drafts/q3-plan.md",
 *         to: "handbook/planning/q3-plan.md"
 *     }
 */
export interface MoveDocumentRequest {
    /**
     * A unique string per logical operation, at most 255 printable ASCII
     * characters. Retrying with the same key and body returns the first outcome
     * instead of acting twice. Idempotency keys are scoped to your key's principal
     * and expire after 24 hours; that expiry is on the replay key, not on your API
     * key.
     */
    "Idempotency-Key": string;
    /** Current whole location of what is moving, from the workspace root. */
    from: string;
    /**
     * Its whole location after the move. The containing directory must
     * differ from `from`'s — use `POST /v1/renames` to rename in place.
     * A document must land inside a folder: the top level holds folders
     * only, so a document moved to a top-level location is a `400`.
     */
    to: string;
    /** Set true to proceed with a move that widens access. */
    acknowledge_access_change?: boolean;
}
