// This file was auto-generated by Fern from our API Definition.

import type * as AgentlefsApi from "../../../../index.js";

/**
 * @example
 *     {
 *         location: "location"
 *     }
 */
export interface RetrieveDocumentRequest {
    /**
     * The document's whole path from the workspace root, filename included,
     * URL-encoded once.
     *
     * The path separators may be sent either way. `handbook/onboarding/day-one.md`
     * and `handbook%2Fonboarding%2Fday-one.md` address the same document, because
     * the value is decoded exactly once before it is used. Write whichever is more
     * natural: a handwritten request usually uses literal separators, while a
     * generated SDK client will percent-encode them, since OpenAPI requires a path
     * parameter's reserved characters to be escaped.
     *
     * What is rejected, in either spelling, is a path that does not mean one
     * definite location: an empty segment (`//`) or a relative segment (`.`, `..`)
     * is a `400`, whether written literally or percent-encoded.
     *
     * This was the document's path WITHIN a folder, alongside a required `folder`
     * query parameter. One location replaces both.
     */
    location: string;
    /** Byte offset, for paging through a document larger than the read cap. */
    offset?: number;
    /**
     * Set to `1` to download the raw file (body bytes with a `Content-Disposition`
     * attachment) rather than the JSON envelope. `offset`, the `ETag`, and the
     * truncation fields do not apply to a download.
     */
    download?: AgentlefsApi.RetrieveDocumentRequestDownload;
}
