// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         "Idempotency-Key": "Idempotency-Key",
 *         location: "handbook/onboarding/day-one.md"
 *     }
 */
export interface UndeleteAtLocationRequest {
    /**
     * A unique string per logical operation, at most 255 printable ASCII
     * characters. Retrying with the same key and body returns the first outcome
     * instead of acting twice. Idempotency keys are scoped to your key's principal
     * and expire after 24 hours; that expiry is on the replay key, not on your API
     * key.
     */
    "Idempotency-Key": string;
    /**
     * The whole location that was deleted, from the workspace root — a
     * document, a directory, or a folder.
     */
    location: string;
}
