// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         location: "location"
 *     }
 */
export interface ExportFolderRequest {
    /** The folder to export, as a whole path from the workspace root. */
    location: string;
}
