// This file was auto-generated by Fern from our API Definition.

export const RetrieveDocumentRequestDownload = {
    One: "1",
} as const;
export type RetrieveDocumentRequestDownload =
    (typeof RetrieveDocumentRequestDownload)[keyof typeof RetrieveDocumentRequestDownload];
