// This file was auto-generated by Fern from our API Definition.

export interface UndeleteAtLocationResponse {
    location?: string | undefined;
    /** How many documents were made current again. */
    restored?: number | undefined;
    /** Documents in the batch with no earlier version to return to. */
    unrestorable?: number | undefined;
    /**
     * How many directories the delete removed came back with it, empty
     * ones included. Undoing the delete of an empty directory restores no
     * documents and one directory, so this is what tells that apart from
     * an undo that found nothing to restore.
     */
    directories?: number | undefined;
}
